# Generated by Django 5.2.8 on 2025-11-18 06:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True)),
                ('sector', models.CharField(choices=[('service', 'Service'), ('industry', 'Industry (Manufacturing)'), ('wholesale', 'Wholesale'), ('retail', 'Retailers')], default='industry', max_length=50)),
                ('start_year', models.IntegerField(default=2025)),
                ('total_years_in_report', models.IntegerField(default=7, help_text='Total columns (e.g., 2 Actual + 5 Projected)')),
                ('has_existing_term_loan', models.BooleanField(default=False)),
                ('new_loan_type', models.CharField(choices=[('term', 'Term Loan Only'), ('wc', 'Working Capital Only'), ('both', 'Both Term Loan & Working Capital')], default='term', max_length=10)),
                ('new_loan_contribution_percent', models.DecimalField(decimal_places=2, default=20.0, help_text="Promoter's contribution %", max_digits=5)),
                ('new_loan_interest_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('new_loan_tenure_years', models.IntegerField(default=5)),
                ('new_loan_moratorium_months', models.IntegerField(default=6)),
                ('new_loan_start_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('page_type', models.CharField(choices=[('operating', 'Operating Statement'), ('asset', 'Balance Sheet - Assets'), ('liability', 'Balance Sheet - Liabilities')], default='operating', max_length=20)),
                ('display_order', models.IntegerField(default=10)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_groups', to='core.financialreport')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('display_order', models.IntegerField(default=10)),
                ('is_custom', models.BooleanField(default=False)),
                ('is_calculated', models.BooleanField(default=False)),
                ('is_total_row', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_rows', to='core.financialgroup')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('Land', 'Land'), ('Building', 'Building'), ('Machinery', 'Machinery'), ('Computers', 'Computers'), ('Furniture', 'Furniture'), ('Racks', 'Racks'), ('Electrification', 'Electrification'), ('Vehicle', 'Vehicle'), ('Software', 'Software'), ('A/c', 'A/c'), ('Other', 'Other investment')], default='Machinery', max_length=50)),
                ('asset_name', models.CharField(help_text="e.g., 'CNC Machine' or 'Other' name", max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('depreciation_rate', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_cost_items', to='core.financialreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportYearSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('year_display', models.CharField(help_text='e.g., 2024-2025', max_length=10)),
                ('year_type', models.CharField(choices=[('Actual', 'Actual'), ('Provisional', 'Provisional'), ('Projected', 'Projected')], max_length=20)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_settings', to='core.financialreport')),
            ],
            options={
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='TermLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_name', models.CharField(default='Existing Loan', max_length=100)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, default=0, help_text='Loan outstanding at audited year', max_digits=14)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('emi', models.DecimalField(decimal_places=2, default=0, help_text='Monthly EMI', max_digits=14)),
                ('remaining_tenure_years', models.IntegerField(default=5, help_text='How many more years to complete the loan?')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='existing_term_loans', to='core.financialreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_data', to='core.financialreport')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='core.financialrow')),
                ('year_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='core.reportyearsetting')),
            ],
            options={
                'ordering': ['year_setting__year'],
                'unique_together': {('row', 'year_setting')},
            },
        ),
    ]
