# Generated by Django 5.2.8 on 2025-11-18 09:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialdata',
            options={},
        ),
        migrations.AlterModelOptions(
            name='financialgroup',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='financialrow',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='financialdata',
            name='report',
        ),
        migrations.RemoveField(
            model_name='financialgroup',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='financialrow',
            name='display_order',
        ),
        migrations.AddField(
            model_name='financialgroup',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialgroup',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='financialrow',
            name='calculation_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='financialrow',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='financialdata',
            name='row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='core.financialrow'),
        ),
        migrations.AlterField(
            model_name='financialdata',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='financialgroup',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='financialgroup',
            name='page_type',
            field=models.CharField(choices=[('operating', 'Operating Statement'), ('asset', 'Assets'), ('liability', 'Liabilities')], max_length=20),
        ),
        migrations.AlterField(
            model_name='financialgroup',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.financialreport'),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='company_name',
            field=models.CharField(default='Untitled Report', max_length=255),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='new_loan_contribution_percent',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='new_loan_start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='sector',
            field=models.CharField(choices=[('service', 'Service'), ('industry', 'Industry (Manufacturing)'), ('wholesale', 'Wholesale'), ('retail', 'Retailers')], default='service', max_length=20),
        ),
        migrations.AlterField(
            model_name='financialrow',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='core.financialgroup'),
        ),
        migrations.AlterField(
            model_name='financialrow',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projectcostitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='projectcostitem',
            name='asset_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projectcostitem',
            name='depreciation_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='reportyearsetting',
            name='year_display',
            field=models.CharField(max_length=20),
        ),
    ]
