# Generated by Django 5.2.8 on 2025-11-20 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_financialdata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcostitem',
            name='purchase_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.reportyearsetting'),
        ),
    ]
