# Generated by Django 5.2.8 on 2025-11-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_projectcostitem_purchase_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcostitem',
            name='is_existing_asset',
            field=models.BooleanField(default=False),
        ),
    ]
