# Generated by Django 5.2.8 on 2025-11-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_projectcostitem_is_existing_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcostitem',
            name='is_second_half_purchase',
            field=models.BooleanField(default=False),
        ),
    ]
