# Generated by Django 5.2.8 on 2025-11-24 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_projectcostitem_is_second_half_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.DecimalField(decimal_places=2, help_text='Total loan amount', max_digits=15)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Annual interest rate (%)', max_digits=5)),
                ('tenure_months', models.IntegerField(help_text='Total loan tenure in months')),
                ('moratorium_months', models.IntegerField(default=0, help_text='Moratorium period (interest-only, no principal)')),
                ('repayment_method', models.CharField(choices=[('EMI', 'Reducing Balance (EMI)'), ('BULLET', 'Bullet Repayment'), ('CUSTOM', 'Custom Schedule')], default='EMI', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_schedules', to='core.financialreport')),
                ('start_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_schedules_started', to='core.reportyearsetting')),
            ],
        ),
        migrations.CreateModel(
            name='LoanYearSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_balance', models.DecimalField(decimal_places=2, help_text='Opening loan balance', max_digits=15)),
                ('annual_interest', models.DecimalField(decimal_places=2, help_text='Interest expense for P&L', max_digits=15)),
                ('annual_principal', models.DecimalField(decimal_places=2, help_text='Principal repayment for Cash Flow', max_digits=15)),
                ('closing_balance', models.DecimalField(decimal_places=2, help_text='Closing loan balance for Balance Sheet', max_digits=15)),
                ('calculated_emi', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly EMI amount', max_digits=15, null=True)),
                ('loan_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_summaries', to='core.loanschedule')),
                ('year_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_summaries', to='core.reportyearsetting')),
            ],
            options={
                'ordering': ['year_setting__year'],
                'unique_together': {('loan_schedule', 'year_setting')},
            },
        ),
    ]
