# Generated by Django 5.2.8 on 2025-12-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_loanschedule_loanyearsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialreport',
            name='existing_wc_interest_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='existing_wc_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='proposed_wc_interest_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='proposed_wc_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='wc_requirement_type',
            field=models.CharField(choices=[('new', 'New Limit'), ('enhancement', 'Enhancement of Existing Limit')], default='new', max_length=20),
        ),
    ]
