# Generated by Django 5.2.8 on 2025-12-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_financialreport_existing_wc_interest_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialreport',
            name='tax_regime',
            field=models.CharField(choices=[('domestic_22', 'Domestic Company (22% + Surcharge + Cess)'), ('llp', 'LLP (30% + Surcharge + Cess)'), ('proprietorship', 'Proprietorship (New Regime Slabs)')], default='domestic_22', max_length=20),
        ),
    ]
