# Generated by Django 5.2.8 on 2025-12-03 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_financialreport_tax_regime'),
    ]

    operations = [
        migrations.AddField(
            model_name='termloan',
            name='original_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Original Loan Amount', max_digits=15),
        ),
        migrations.AddField(
            model_name='termloan',
            name='repayment_method',
            field=models.CharField(choices=[('EMI', 'Reducing Balance (EMI)'), ('BULLET', 'Bullet Repayment'), ('CUSTOM', 'Custom Schedule')], default='EMI', max_length=20),
        ),
        migrations.AddField(
            model_name='termloan',
            name='start_date',
            field=models.DateField(blank=True, help_text='Loan start date', null=True),
        ),
        migrations.AddField(
            model_name='termloan',
            name='tenure_months',
            field=models.IntegerField(default=60, help_text='Total Tenure in Months'),
        ),
        migrations.AlterField(
            model_name='termloan',
            name='outstanding_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Loan outstanding at audited year (Manual Override)', max_digits=14),
        ),
        migrations.AlterField(
            model_name='termloan',
            name='remaining_tenure_years',
            field=models.IntegerField(default=5, help_text='How many more years to complete the loan? (Manual Override)'),
        ),
        migrations.CreateModel(
            name='TermLoanYearSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('annual_interest', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('annual_principal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('calculated_emi', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('term_loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_summaries', to='core.termloan')),
                ('year_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_loan_summaries', to='core.reportyearsetting')),
            ],
            options={
                'ordering': ['year_setting__year'],
                'unique_together': {('term_loan', 'year_setting')},
            },
        ),
    ]
