# Generated by Django 5.2.8 on 2025-12-03 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_termloanyearsummary_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanyearsummary',
            options={'ordering': ['year_setting__year', 'id']},
        ),
        migrations.AlterUniqueTogether(
            name='loanyearsummary',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='loanyearsummary',
            name='year_label',
            field=models.CharField(blank=True, help_text='e.g. FY 2024-25', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='loanyearsummary',
            name='year_setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_summaries', to='core.reportyearsetting'),
        ),
    ]
