# Generated by Django 5.2.8 on 2025-12-06 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_loanyearsummary_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExistingWorkingCapitalLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(default='Existing Bank', max_length=100)),
                ('sanctioned_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='existing_wc_loans', to='core.financialreport')),
            ],
        ),
    ]
