# Generated by Django 5.2.8 on 2025-12-09 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_existingworkingcapitalloan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Partner A Drawing', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to='core.financialreport')),
                ('year_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to='core.reportyearsetting')),
            ],
            options={
                'ordering': ['year_setting__year', 'id'],
            },
        ),
    ]
