# Generated by Django 5.2.8 on 2025-12-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_drawing'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialgroup',
            name='cf_bucket',
            field=models.CharField(choices=[('operating', 'Operating Activities'), ('investing', 'Investing Activities'), ('financing', 'Financing Activities'), ('cash_equivalent', 'Cash & Equivalents (Ignore)')], default='operating', help_text='Cash flow activity bucket', max_length=20),
        ),
        migrations.AddField(
            model_name='financialgroup',
            name='nature',
            field=models.CharField(choices=[('asset', 'Asset (Increase = Outflow)'), ('liability', 'Liability (Increase = Inflow)'), ('pnl_income', 'P&L Income'), ('pnl_expense', 'P&L Expense'), ('pnl_noncash', 'P&L Non-Cash (Add Back)')], default='asset', help_text='Direction of cash impact', max_length=20),
        ),
        migrations.AddField(
            model_name='financialgroup',
            name='system_tag',
            field=models.CharField(blank=True, help_text="Unique logic identifier e.g. 'current_assets'", max_length=50, null=True),
        ),
    ]
