# Generated by Django 5.2.8 on 2025-12-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_cash_flow_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrow',
            name='system_tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
