# Generated by Django 5.2.8 on 2026-03-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_financialrow_system_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialreport',
            name='start_year',
            field=models.IntegerField(default=2026),
        ),
    ]
